In [1]:
from PIL import Image
import pytesseract
import os
from pillow_heif import register_heif_opener
register_heif_opener()

import keras_ocr
    



In [2]:
# Image formatting
def heic_to_png(heic_filepath, png_filepath=None, overwrite=True):
    if not png_filepath:
        png_filepath = '.'.join(heic_filepath.split('.')[:-1]+ ['PNG'])
    if os.path.exists(png_filepath) and not overwrite:
        print('File already exists')
        return png_filepath
    try:
        image = Image.open(heic_filepath)
        image.save(png_filepath, "PNG")
        print(f"Converted {heic_filepath} to {png_filepath}")
        return png_filepath
    except Exception as e:
        print(f"Error converting {heic_filepath}: {e}")
    

# Example usage:
heic_file = os.path.join('..', 'data', 'IMG_5978.HEIC')
png_file = heic_to_png(heic_file)


Converted ../data/IMG_5978.HEIC to ../data/IMG_5978.PNG


In [3]:
# Set the path to the Tesseract executable (if not in PATH)
# pytesseract.pytesseract.tesseract_cmd = r'<full_path_to_your_tesseract_executable>'

# Load the image
#image = Image.open(png_file)

# Perform OCR and extract text
#text = pytesseract.image_to_string(image)

# Print the extracted text
#print(text)

pipeline = keras_ocr.pipeline.Pipeline()
images = [keras_ocr.tools.read(png_file)]
predictions = pipeline.recognize(images)
for group in predictions:
    for detection in group:
        text = detection[0]
        print(text)


Looking for /Users/garveyli/.keras-ocr/craft_mlt_25k.h5
Instructions for updating:
Use `tf.image.resize(...method=ResizeMethod.BILINEAR...)` instead.
Looking for /Users/garveyli/.keras-ocr/crnn_kurapan.h5
1/1 [==============================] - 5s 5s/step


/opt/anaconda3/envs/cv/lib/python3.10/site-packages/shapely/constructive.py:1353: RuntimeWarning: divide by zero encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)
/opt/anaconda3/envs/cv/lib/python3.10/site-packages/shapely/constructive.py:1353: RuntimeWarning: invalid value encountered in oriented_envelope
  return lib.oriented_envelope(geometry, **kwargs)


3/3 [==============================] - 3s 832ms/step
bdy
ingredients
nounseaving
pasteurized
ad
milk
and
cream
salt
guar
gum
natamycin
a
natural
discard
seal
vab
2
10
mold
toa
inhibitory
rinse
tub
cheese
culture
replace
ld
contains
fiber
o
verary
o0
milk
o
s
kraft
heinz
foods
suyars
loa
company
lg
s
chicago
il
60601
o
ein
inc
b
aoded
sugars
plastic
o0o
do
not
freeze
keep
refrigerated
tub

on
pochn
best
l
if
used
by
date
showin
for
best
quality
use
within
alo
ramizne
kraftheinz
10
days
too
of
uoh
opening
potssim
0o0
creamcheese
com
patents
wwwkraftheinz
compatents
100063414


In [4]:
text

'100063414'

In [5]:
group

[('bdy',
  array([[1063.125 , 1441.125 ],
         [1145.8125, 1441.125 ],
         [1145.8125, 1496.25  ],
         [1063.125 , 1496.25  ]], dtype=float32)),
 ('ingredients',
  array([[1177.7751, 1438.1288],
         [1455.2434, 1449.9359],
         [1452.6919, 1509.8951],
         [1175.2236, 1498.0879]], dtype=float32)),
 ('nounseaving',
  array([[ 756.    , 1445.0625],
         [ 905.625 , 1445.0625],
         [ 905.625 , 1504.125 ],
         [ 756.    , 1504.125 ]], dtype=float32)),
 ('pasteurized',
  array([[1457.5323, 1448.5431],
         [1742.7451, 1463.8224],
         [1739.4435, 1525.4501],
         [1454.2307, 1510.1709]], dtype=float32)),
 ('ad',
  array([[ 704.8125, 1460.8125],
         [ 744.1875, 1460.8125],
         [ 744.1875, 1504.125 ],
         [ 704.8125, 1504.125 ]], dtype=float32)),
 ('milk',
  array([[1745.9366, 1470.2656],
         [1853.3063, 1476.9762],
         [1849.7825, 1533.3577],
         [1742.4127, 1526.647 ]], dtype=float32)),
 ('and',
  array([[185